CompanyTraining/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Courses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CompanyTraining/force-app/main/default/objects/Course__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advanced</fullName>
            </value>
            <value>
                <fullName>Beginner</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CompanyTraining/force-app/main/default/objects/Course__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Test Analyst</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CompanyTraining/force-app/main/default/objects/Course_Assignment__c/Course_Assignment__c.object-meta.xml
<CustomObject>
    <label>Course Assignment</label>
    <nameField>
        <displayFormat>Asgn-{0000}</displayFormat>
        <label>Course Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CompanyTraining/force-app/main/default/objects/Course_Assignment__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Assignments</relationshipLabel>
    <relationshipName>Course_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CompanyTraining/force-app/main/default/objects/Course_Assignment__c/fields/Trainee__c.field-meta.xml
<CustomField>
    <fullName>Trainee__c</fullName>
    <label>Trainee</label>
    <referenceTo>Trainee__c</referenceTo>
    <relationshipLabel>Course Assignments</relationshipLabel>
    <relationshipName>Course_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CompanyTraining/force-app/main/default/classes/TrainingCourseController.cls
public class TrainingCourseController{
    
    
    @AuraEnabled(cacheable = true)
    public static list<TraineeCourse> findCourses(String traineeId, String position, String level){
        List<TraineeCourse> traineeCourses = new List<TraineeCourse>();
        Set<Id> assignedCourses = new Set<Id>();
        
        for(Course_Assignment__c c: [SELECT Course__c from Course_Assignment__c where Trainee__c =: traineeId]){
            assignedCourses.add(c.Course__c);
        }
        String query = 'SELECT Id, Name, Title__c,Description__c, Image_URL__c, Level__c,Position__c FROM Course__c where Name != null ';
        if(position != 'All'){
            query += ' and Position__c =: position ';
        }
        if(level != 'All'){
            query += ' and Level__c =: level ';
        }
        list<Course__c> myrecords = Database.query(query);
        for(Course__c c: myrecords){
            system.debug('###:'+traineeId+'::'+assignedCourses+'::'+assignedCourses.contains(c.Id));
            Boolean isAssigned = assignedCourses.contains(c.Id);
            TraineeCourse tc = new TraineeCourse(c.Id,c.Name,c.Title__c,c.Description__c, isAssigned, c.Image_URL__c);
            traineeCourses.add(tc);
        }
        return traineeCourses;
    }
    
    @AuraEnabled(cacheable = true)
    public static Course__c getCourse(String courseId){
        system.debug('@@@:'+courseId +'::'+[SELECT Id, Name, Title__c,Description__c, Image_URL__c, Level__c,Position__c FROM Course__c where Id =: courseId limit 1]);
        return [SELECT Id, Name, Title__c,Description__c, Image_URL__c, Level__c,Position__c FROM Course__c where Id =: courseId limit 1];
    }    
    
    @AuraEnabled(Cacheable=false)
    public static void saveAssignement(String traineeId, String courseId){
        Course_Assignment__c assignment = new Course_Assignment__c(Trainee__c = traineeId, Course__c = courseId);
        insert assignment;
    }
    
    public class TraineeCourse{
        
        @AuraEnabled public String courseId{get;set;}
        @AuraEnabled public String courseName{get;set;}
        @AuraEnabled public String courseTitle{get;set;}
        @AuraEnabled public String courseDescription{get;set;}
        @AuraEnabled public Boolean isAssigned{get;set;}
        @AuraEnabled public String courseImage{get;set;}
        
        public TraineeCourse(String courseId, String courseName, String courseTitle, String courseDescription, Boolean isAssigned, String courseImage){
            this.courseId = courseId;
            this.courseName = courseName;
            this.courseTitle = courseTitle;
            this.courseDescription = courseDescription;
            this.isAssigned= isAssigned;
            this.courseImage= courseImage;
        }
        
    }
}